export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  SET_DOCTORS_LIST: "SET_DOCTORS_LIST",
  SET_DOCTORS_APPOINTMENT_lIST: "SET_DOCTORS_APPOINTMENT_lIST",
  SET_PATIENT_INFO: "SET_PATIENT_INFO",
  SET_PATIENTS_LIST: "SET_PATIENTS_LIST",
  SET_SERVICES_LIST: "SET_SERVICES_LIST",
  SET_NURSES_LIST: "SET_NURSES_LIST",
};
